# Generated by Django 2.2.3 on 2019-07-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djropbox', '0002_auto_20190711_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djropbox.BoxUser'),
        ),
        migrations.DeleteModel(
            name='DjropboxUser',
        ),
    ]
