# Generated by Django 2.2.3 on 2019-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djropbox', '0003_auto_20190712_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfile',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
